// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVg2u5iMs7nxvRtTD8Cd-_pb1OpMko4Rs',
    appId: '1:232758527299:web:6d88c56e53bc94631c5bf6',
    messagingSenderId: '232758527299',
    projectId: 'chatapp-753cf',
    authDomain: 'chatapp-753cf.firebaseapp.com',
    storageBucket: 'chatapp-753cf.appspot.com',
    measurementId: 'G-6P8JG73B0D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRklN69JsAyjzLY3Bz3VRl_pbU9RNo6ro',
    appId: '1:232758527299:android:2a5aca1c7b663b431c5bf6',
    messagingSenderId: '232758527299',
    projectId: 'chatapp-753cf',
    storageBucket: 'chatapp-753cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5BQaRVMCycG7C1aEvJEdKoDp4K6a6xmI',
    appId: '1:232758527299:ios:99e2b9857ecc3dce1c5bf6',
    messagingSenderId: '232758527299',
    projectId: 'chatapp-753cf',
    storageBucket: 'chatapp-753cf.appspot.com',
    androidClientId: '232758527299-tqnhih05uvhfduid1d692hvinkl6l9b2.apps.googleusercontent.com',
    iosClientId: '232758527299-plua0r9je3chvsctls65hramoi8dnif3.apps.googleusercontent.com',
    iosBundleId: 'com.example.listviewInBlocpattern',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5BQaRVMCycG7C1aEvJEdKoDp4K6a6xmI',
    appId: '1:232758527299:ios:99e2b9857ecc3dce1c5bf6',
    messagingSenderId: '232758527299',
    projectId: 'chatapp-753cf',
    storageBucket: 'chatapp-753cf.appspot.com',
    androidClientId: '232758527299-tqnhih05uvhfduid1d692hvinkl6l9b2.apps.googleusercontent.com',
    iosClientId: '232758527299-plua0r9je3chvsctls65hramoi8dnif3.apps.googleusercontent.com',
    iosBundleId: 'com.example.listviewInBlocpattern',
  );
}
